services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/rails
      - ./db:/rails/db
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=development
    env_file:
        - .env
    entrypoint: ["sh", "-c", "rm -f /rails/tmp/pids/server.pid && bundle exec rails server -b 0.0.0.0 -p 3000"]

